using System;
using Application.Activities.DTOs;
using Application.Core;
using Application.Interfaces;
using AutoMapper;
using Domain;
using FluentValidation;
using MediatR;
using Persistence;

namespace Application.Activities.Commands;

// After behaviors like validation, Mediator will come to here according to the pipeline.
public class CreateActivity
{
    // It tells Mediator what response to expect when this Command is handled.
    // When Mediator sends this Command, it expects to get back Result<string>.
    // returns string id. which is an instance of Result class where T is string.
    // IRequest has a contract (what), it expects a response of type string.
    public class Command : IRequest<Result<string>>
    {
        // Mediator.Send(new CreateActivity.Command { ActivityDto = activityDto },
        // so Mediator passes the ActivityDto in the Command.
        public required CreateActivityDto ActivityDto { get; set; }
    }

    // IRequestHandler<Command, Result<string>> tells Mediator that the handler processes CreateActivity.Command and returns Result<string>.
    // This Handler handles requests of type CreateActivity.Command.
    // DI container will inject AppDbContext, IMapper by checking Program.cs.
    // Interface IMapper's contract (what) is it has to map source object to destination object.
    // The contract (What) of IRequestHandler<Command, string> is it processes a request (Command) and product a string response.
    // When DI container injects IUserAccessor userAccessor, it actually injects UserAccessor because UserAccessor is a concrete class that implements IUserAccessor.
    public class Handler(AppDbContext context, IMapper mapper, IUserAccessor userAccessor) : IRequestHandler<Command, Result<string>>
    {
        // Handle must return the type specified by the Command so the Controller will get what it expects in the end.
        public async Task<Result<string>> Handle(Command request, CancellationToken cancellationToken)
        {
            // get user through GetUserAsync in UserAccessor.cs.
            var user = await userAccessor.GetUserAsync();

            // <Activity> is the destination. (request.ActivityDto) is the source.
            // DI container injects concrete mapper instance (how), which has been configured to use CreateMap<CreateActivityDto, Activity>() (defined in MappingProfiles.cs).
            // to map request.ActivityDto object from ActivitiesController to create a new instance of Activity entity from Domain Layer.
            // Handler just needs to know Map<Activity>(request.ActivityDto) fulfills Interface IMapper's contract, then passes data to concrete instance mapper.Map().
            // AutoMapper first instantiates a new Activity class, then immediately copies property values from ActivityDto to it.
            // For properties without values after copying, it will set default values according to C#.
            var activity = mapper.Map<Activity>(request.ActivityDto);

            // not accessing the database to get value generated by the database, dont use AddAsync.
            // activity holds new Activity object from the domain layer populated by ActivityDto.
            context.Activities.Add(activity);

            // attendee is created according to ActivityAttendee object. DateTime follows default current date and time.
            var attendee = new ActivityAttendee
            {
                ActivityId = activity.Id,
                UserId = user.Id,
                IsHost = true,
            };

            // When an activity is created, the user is added to the ActivityAttendee table of the Activity. 
            // EF Core accesses activity.Attendees through navigation property in Activity entity.
            activity.Attendees.Add(attendee);

            // .Add() doesn't immediately write to the database, it tells EF's DbContext to mark the request.Activity object in an "Added" state.
            // SaveChangesAsync makes EF execute SQL query to add request.Activity.
            var result = await context.SaveChangesAsync(cancellationToken) > 0;

            if (!result) return Result<string>.Failure("Failed to create the activity", 400);

            // After SaveChangesAsync completes, EF updates the request.Activity with Id generated by the database.
            // return activity Id to use in the client side.
            return Result<string>.Success(activity.Id);
        }
    }
}
